"""empty message

Revision ID: 048023a44a1b
Revises: b6e6656d5d35
Create Date: 2021-04-02 16:58:05.063402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '048023a44a1b'
down_revision = 'b6e6656d5d35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('communication_email', sa.String(length=120), nullable=True))
    op.add_column('company', sa.Column('correo_apikey_test', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('correo_id_test', sa.String(length=50), nullable=True))
    op.add_column('company', sa.Column('correo_test', sa.Boolean(), nullable=True))
    op.add_column('company', sa.Column('platform_access_token', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('platform_token_type', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'platform_token_type')
    op.drop_column('company', 'platform_access_token')
    op.drop_column('company', 'correo_test')
    op.drop_column('company', 'correo_id_test')
    op.drop_column('company', 'correo_apikey_test')
    op.drop_column('company', 'communication_email')
    # ### end Alembic commands ###
