"""empty message

Revision ID: 059c8afbe99f
Revises: 6eba73373f23
Create Date: 2020-12-17 12:41:48.357858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059c8afbe99f'
down_revision = '6eba73373f23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('accion_reaccion', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'accion_reaccion')
    # ### end Alembic commands ###
