"""empty message

Revision ID: 08fdaeab2ef2
Revises: f312379b7140
Create Date: 2021-01-28 10:17:43.302046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08fdaeab2ef2'
down_revision = 'f312379b7140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('order_fecha_compra', sa.DateTime(), nullable=True))
    op.add_column('producto', sa.Column('valido', sa.Boolean(), nullable=True))
    op.add_column('producto', sa.Column('valido_motivo', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'valido_motivo')
    op.drop_column('producto', 'valido')
    op.drop_column('order', 'order_fecha_compra')
    # ### end Alembic commands ###
