"""empty message

Revision ID: 0ab1db250f68
Revises: e307ac29f1b6
Create Date: 2021-08-11 19:42:22.205200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab1db250f68'
down_revision = 'e307ac29f1b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_uid', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'company_uid')
    # ### end Alembic commands ###
