"""empty message

Revision ID: 24d645bd51ee
Revises: 08fdaeab2ef2
Create Date: 2021-02-04 16:11:49.880277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d645bd51ee'
down_revision = '08fdaeab2ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('identification', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_customer_identification'), 'customer', ['identification'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customer_identification'), table_name='customer')
    op.drop_column('customer', 'identification')
    # ### end Alembic commands ###
