"""empty message

Revision ID: 2df964c11791
Revises: 3c002e4075bc
Create Date: 2020-12-15 07:54:37.387509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2df964c11791'
down_revision = '3c002e4075bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('image', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'image')
    # ### end Alembic commands ###
