"""empty message

Revision ID: 34263c116b50
Revises: 035f26b2e77e
Create Date: 2021-01-06 16:12:55.421864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34263c116b50'
down_revision = '035f26b2e77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('accion_cambiar_por_desc', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'accion_cambiar_por_desc')
    # ### end Alembic commands ###
