"""empty message

Revision ID: 4bcfda831079
Revises: 0ab1db250f68
Create Date: 2021-09-16 12:07:02.245352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bcfda831079'
down_revision = '0ab1db250f68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_company_timestamp'), 'company', ['timestamp'], unique=False)
    op.add_column('customer', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_customer_timestamp'), 'customer', ['timestamp'], unique=False)
    op.add_column('producto', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_producto_timestamp'), 'producto', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_timestamp'), table_name='producto')
    op.drop_column('producto', 'timestamp')
    op.drop_index(op.f('ix_customer_timestamp'), table_name='customer')
    op.drop_column('customer', 'timestamp')
    op.drop_index(op.f('ix_company_timestamp'), table_name='company')
    op.drop_column('company', 'timestamp')
    # ### end Alembic commands ###
