"""empty message

Revision ID: 4f82640e96cd
Revises: d4f5c0699db9
Create Date: 2020-12-30 16:11:09.004723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f82640e96cd'
down_revision = 'd4f5c0699db9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_company_store_id'), 'company', ['store_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_store_id'), table_name='company')
    # ### end Alembic commands ###
