"""empty message

Revision ID: a18cddfb9d9e
Revises: fbb17e1f6e16
Create Date: 2021-07-27 08:16:01.197949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18cddfb9d9e'
down_revision = 'fbb17e1f6e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('accion_cambiar_por_prod_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'accion_cambiar_por_prod_id')
    # ### end Alembic commands ###
