"""empty message

Revision ID: b6e6656d5d35
Revises: 77f4cb131a02
Create Date: 2021-04-02 16:11:48.831203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e6656d5d35'
down_revision = '77f4cb131a02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('store', sa.Column('communication_email', sa.String(length=120), nullable=True))
    op.add_column('store', sa.Column('correo_apikey_test', sa.String(length=50), nullable=True))
    op.add_column('store', sa.Column('correo_id_test', sa.String(length=50), nullable=True))
    op.add_column('store', sa.Column('correo_test', sa.Boolean(), nullable=True))
    op.add_column('store', sa.Column('platform_access_token', sa.String(length=64), nullable=True))
    op.add_column('store', sa.Column('platform_token_type', sa.String(length=30), nullable=True))
    op.add_column('store', sa.Column('store_country', sa.String(length=20), nullable=True))
    op.add_column('store', sa.Column('store_main_currency', sa.String(length=20), nullable=True))
    op.add_column('store', sa.Column('store_main_language', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('store', 'store_main_language')
    op.drop_column('store', 'store_main_currency')
    op.drop_column('store', 'store_country')
    op.drop_column('store', 'platform_token_type')
    op.drop_column('store', 'platform_access_token')
    op.drop_column('store', 'correo_test')
    op.drop_column('store', 'correo_id_test')
    op.drop_column('store', 'correo_apikey_test')
    op.drop_column('store', 'communication_email')
    # ### end Alembic commands ###
