"""empty message

Revision ID: c2eae45c1ed8
Revises: 059c8afbe99f
Create Date: 2020-12-17 15:44:01.200885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2eae45c1ed8'
down_revision = '059c8afbe99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atributo_descripcion'), 'atributo', ['descripcion'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_atributo_descripcion'), table_name='atributo')
    op.drop_table('atributo')
    # ### end Alembic commands ###
