"""empty message

Revision ID: c7a31ade57d4
Revises: 
Create Date: 2021-08-13 20:48:45.329077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a31ade57d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('company_uid', sa.String(length=150), nullable=True))
    op.add_column('customer', sa.Column('customer_uid', sa.String(length=150), nullable=True))
    op.add_column('order', sa.Column('order_uid', sa.String(length=150), nullable=True))
    op.add_column('producto', sa.Column('accion_cambiar_por_prod_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producto', 'accion_cambiar_por_prod_id')
    op.drop_column('order', 'order_uid')
    op.drop_column('customer', 'customer_uid')
    op.drop_column('company', 'company_uid')
    # ### end Alembic commands ###
