"""empty message

Revision ID: d4f5c0699db9
Revises: 
Create Date: 2020-12-29 10:40:57.415154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4f5c0699db9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atributo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atributo_descripcion'), 'atributo', ['descripcion'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=True),
    sa.Column('store_id', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=64), nullable=True),
    sa.Column('admin_email', sa.String(length=120), nullable=True),
    sa.Column('logo', sa.String(length=120), nullable=True),
    sa.Column('contact_name', sa.String(length=64), nullable=True),
    sa.Column('contact_phone', sa.String(length=15), nullable=True),
    sa.Column('contact_email', sa.String(length=120), nullable=True),
    sa.Column('correo_usado', sa.String(length=64), nullable=True),
    sa.Column('correo_apikey', sa.String(length=50), nullable=True),
    sa.Column('correo_id', sa.String(length=50), nullable=True),
    sa.Column('shipping_address', sa.String(length=64), nullable=True),
    sa.Column('shipping_number', sa.String(length=64), nullable=True),
    sa.Column('shipping_floor', sa.String(length=64), nullable=True),
    sa.Column('shipping_zipcode', sa.String(length=64), nullable=True),
    sa.Column('shipping_city', sa.String(length=64), nullable=True),
    sa.Column('shipping_province', sa.String(length=64), nullable=True),
    sa.Column('shipping_country', sa.String(length=64), nullable=True),
    sa.Column('shipping_info', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=64), nullable=True),
    sa.Column('number', sa.String(length=10), nullable=True),
    sa.Column('floor', sa.String(length=10), nullable=True),
    sa.Column('zipcode', sa.String(length=8), nullable=True),
    sa.Column('locality', sa.String(length=64), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('province', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.Integer(), nullable=True),
    sa.Column('order_original_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prod_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('accion', sa.String(length=10), nullable=True),
    sa.Column('accion_reaccion', sa.Boolean(), nullable=True),
    sa.Column('accion_cambiar_por', sa.Integer(), nullable=True),
    sa.Column('accion_cantidad', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.String(length=50), nullable=True),
    sa.Column('image', sa.String(length=100), nullable=True),
    sa.Column('promo_descuento', sa.Float(), nullable=True),
    sa.Column('promo_nombre', sa.String(length=10), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_producto_prod_id'), 'producto', ['prod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_prod_id'), table_name='producto')
    op.drop_table('producto')
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    op.drop_table('company')
    op.drop_index(op.f('ix_atributo_descripcion'), table_name='atributo')
    op.drop_table('atributo')
    # ### end Alembic commands ###
