"""empty message

Revision ID: de3c2290aaf0
Revises: 8d1b06b52fc8
Create Date: 2024-02-26 20:08:10.889523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de3c2290aaf0'
down_revision = '8d1b06b52fc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('metodo_envio_sucursal_name', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'metodo_envio_sucursal_name')
    # ### end Alembic commands ###
