"""empty message

Revision ID: e007b3312af2
Revises: c2eae45c1ed8
Create Date: 2020-12-17 16:23:02.600112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e007b3312af2'
down_revision = 'c2eae45c1ed8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('producto', sa.Column('prod_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_producto_prod_id'), 'producto', ['prod_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_producto_prod_id'), table_name='producto')
    op.drop_column('producto', 'prod_id')
    # ### end Alembic commands ###
