"""empty message

Revision ID: e8ccac4d528b
Revises: 24d645bd51ee
Create Date: 2021-02-16 12:43:03.718303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8ccac4d528b'
down_revision = '24d645bd51ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('gastos_cupon', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('gastos_gateway', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('gastos_promocion', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('gastos_shipping_customer', sa.Float(), nullable=True))
    op.add_column('order', sa.Column('gastos_shipping_owner', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'gastos_shipping_owner')
    op.drop_column('order', 'gastos_shipping_customer')
    op.drop_column('order', 'gastos_promocion')
    op.drop_column('order', 'gastos_gateway')
    op.drop_column('order', 'gastos_cupon')
    # ### end Alembic commands ###
