"""Tables

Revision ID: edfdcb5623b0
Revises: 
Create Date: 2020-12-07 20:42:16.424044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfdcb5623b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('identification', sa.String(length=20), nullable=True),
    sa.Column('default_address', sa.String(length=120), nullable=True),
    sa.Column('addresses', sa.String(length=120), nullable=True),
    sa.Column('total_spent', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('last_order_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=True)
    op.create_index(op.f('ix_customer_identification'), 'customer', ['identification'], unique=False)
    op.create_index(op.f('ix_customer_name'), 'customer', ['name'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('customer', sa.String(length=120), nullable=True),
    sa.Column('products', sa.String(length=120), nullable=True),
    sa.Column('coupon', sa.String(length=120), nullable=True),
    sa.Column('discount', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Integer(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=120), nullable=True),
    sa.Column('language', sa.String(length=120), nullable=True),
    sa.Column('shipping', sa.String(length=120), nullable=True),
    sa.Column('shipping_cost_owner', sa.Integer(), nullable=True),
    sa.Column('shipping_cost_customer', sa.Integer(), nullable=True),
    sa.Column('shipping_pickup_details', sa.String(length=120), nullable=True),
    sa.Column('storefront', sa.String(length=120), nullable=True),
    sa.Column('shipping_status', sa.String(length=120), nullable=True),
    sa.Column('payment_status', sa.String(length=120), nullable=True),
    sa.Column('next_Action', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_created_at'), 'orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_orders_customer'), 'orders', ['customer'], unique=False)
    op.create_index(op.f('ix_orders_number'), 'orders', ['number'], unique=False)
    op.create_index(op.f('ix_orders_products'), 'orders', ['products'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_products'), table_name='orders')
    op.drop_index(op.f('ix_orders_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_customer'), table_name='orders')
    op.drop_index(op.f('ix_orders_created_at'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_customer_name'), table_name='customer')
    op.drop_index(op.f('ix_customer_identification'), table_name='customer')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.drop_table('customer')
    # ### end Alembic commands ###
