"""empty message

Revision ID: fbb17e1f6e16
Revises: 3748106cdcaf
Create Date: 2021-05-05 11:44:13.706645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbb17e1f6e16'
down_revision = '3748106cdcaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('instructions', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'instructions')
    # ### end Alembic commands ###
