"""empty message

Revision ID: fe5da1f8c63e
Revises: edfdcb5623b0
Create Date: 2020-12-15 06:13:59.849957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe5da1f8c63e'
down_revision = 'edfdcb5623b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Order_Number', sa.Integer(), nullable=True),
    sa.Column('Order_Original_Id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_timestamp'), 'order', ['timestamp'], unique=False)
    op.create_table('producto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('variant', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_customer', table_name='orders')
    op.drop_index('ix_orders_number', table_name='orders')
    op.drop_index('ix_orders_products', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_customer_identification', table_name='customer')
    op.drop_column('customer', 'default_address')
    op.drop_column('customer', 'identification')
    op.drop_column('customer', 'last_order_id')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'active')
    op.drop_column('customer', 'total_spent')
    op.drop_column('customer', 'addresses')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('addresses', sa.VARCHAR(length=120), nullable=True))
    op.add_column('customer', sa.Column('total_spent', sa.INTEGER(), nullable=True))
    op.add_column('customer', sa.Column('active', sa.BOOLEAN(), nullable=True))
    op.add_column('customer', sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
    op.add_column('customer', sa.Column('last_order_id', sa.INTEGER(), nullable=True))
    op.add_column('customer', sa.Column('identification', sa.VARCHAR(length=20), nullable=True))
    op.add_column('customer', sa.Column('default_address', sa.VARCHAR(length=120), nullable=True))
    op.create_index('ix_customer_identification', 'customer', ['identification'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('number', sa.INTEGER(), nullable=True),
    sa.Column('customer', sa.VARCHAR(length=120), nullable=True),
    sa.Column('products', sa.VARCHAR(length=120), nullable=True),
    sa.Column('coupon', sa.VARCHAR(length=120), nullable=True),
    sa.Column('discount', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.INTEGER(), nullable=True),
    sa.Column('total', sa.INTEGER(), nullable=True),
    sa.Column('currency', sa.VARCHAR(length=120), nullable=True),
    sa.Column('language', sa.VARCHAR(length=120), nullable=True),
    sa.Column('shipping', sa.VARCHAR(length=120), nullable=True),
    sa.Column('shipping_cost_owner', sa.INTEGER(), nullable=True),
    sa.Column('shipping_cost_customer', sa.INTEGER(), nullable=True),
    sa.Column('shipping_pickup_details', sa.VARCHAR(length=120), nullable=True),
    sa.Column('storefront', sa.VARCHAR(length=120), nullable=True),
    sa.Column('shipping_status', sa.VARCHAR(length=120), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=120), nullable=True),
    sa.Column('next_Action', sa.VARCHAR(length=120), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_products', 'orders', ['products'], unique=False)
    op.create_index('ix_orders_number', 'orders', ['number'], unique=False)
    op.create_index('ix_orders_customer', 'orders', ['customer'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.drop_table('producto')
    op.drop_index(op.f('ix_order_timestamp'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
